name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no mwangi@165.232.106.47 << 'EOF'
            cd /home/mwangi/django_cloud/frontend
            git pull origin main
            sudo nginx -t && \
            sudo systemctl restart nginx && \
            sudo systemctl status nginx
          EOF
